# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Set environment variables
      env:
        USER: ${{ secrets.DB_USER }}
        PASSWORD: ${{ secrets.DB_PASSWORD }}
        DBNAME: ${{ secrets.DB_NAME }}
        SSLMODE: ${{ secrets.DB_SSLMODE }}
      run: |
        echo "Environment variables set"

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

